#!/usr/bin/env node
// Regenerates dev/seed/data.json from the round-3 shared data file
// (design/round3/_shared/assets/data.js), PLAN.md §6.10.
//
// Node standard library only. data.js is an ES5 IIFE that assigns
// window.SPOKARES; it is evaluated in a sandbox with a stub `window`, the
// helper functions (`fn`) are dropped, and the rest is written as JSON.
//
// Usage: node wordpress/dev/seed/convert.mjs [--check]
//   --check  exit 1 if data.json is out of date (for CI), write nothing.

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../..');
const src = path.join(root, 'design/round3/_shared/assets/data.js');
const out = path.join(here, 'data.json');

const code = fs.readFileSync(src, 'utf8');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(code, sandbox, { filename: src, timeout: 2000 });

const data = sandbox.window.SPOKARES;
if (!data || typeof data !== 'object') {
  console.error('convert: data.js did not define window.SPOKARES');
  process.exit(1);
}
delete data.fn;

const json = JSON.stringify(
  {
    _generated: 'Generated by dev/seed/convert.mjs from design/round3/_shared/assets/data.js. Do not edit by hand; edit data.js and re-run.',
    ...data,
  },
  null,
  1
) + '\n';

if (process.argv.includes('--check')) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current !== json) {
    console.error('convert: dev/seed/data.json is out of date; run node wordpress/dev/seed/convert.mjs');
    process.exit(1);
  }
  console.log('convert: data.json is up to date');
  process.exit(0);
}

fs.writeFileSync(out, json);
console.log(
  `convert: wrote ${path.relative(root, out)} (${data.documents.length} documents, ` +
  `${data.events.length} events, ${data.pastExercises.length} past exercises, ${data.rota.length} rota rows, ` +
  `${data.winlink.assignments.length} Winlink assignments)`
);
