<?php
/**
 * Old URLs (§5.6): 301 to the new pages, 410 for pages that are gone (both
 * roster URLs included), WordPress's 404 for the rest. Spam URLs injected
 * during the hack (index.php?option=com_…, /index.php/…) that aren't in the
 * map get 410.
 *
 * The map is generated by wordpress/tools/redirects/gen-redirect-map.mjs into
 * redirect-map.php: 'path?sorted-query' => [ status, target ].
 *
 * Also: WordPress never "guesses" a page for an unknown URL (that would send
 * spam URLs somewhere real), and a request for a missing file under
 * wp-content/ is a plain 404.
 *
 * @package spokares-hardening
 */

defined( 'ABSPATH' ) || exit;

/**
 * The map (loaded once).
 */
function spokares_hard_redirect_map(): array {
	static $map = null;
	if ( null === $map ) {
		$file = __DIR__ . '/redirect-map.php';
		$map  = is_readable( $file ) ? (array) require $file : array();
	}
	return $map;
}

/**
 * The request's path (decoded) and its query with the parameters sorted.
 *
 * @return array{0:string,1:string}
 */
function spokares_hard_request_key(): array {
	$uri   = isset( $_SERVER['REQUEST_URI'] ) ? (string) wp_unslash( $_SERVER['REQUEST_URI'] ) : '/'; // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- only compared with map keys, never printed.
	$path  = (string) wp_parse_url( $uri, PHP_URL_PATH );
	$query = (string) wp_parse_url( $uri, PHP_URL_QUERY );
	$path  = rawurldecode( '' !== $path ? $path : '/' );
	$base  = (string) wp_parse_url( home_url( '/' ), PHP_URL_PATH );
	if ( '' !== $base && '/' !== $base && str_starts_with( $path, rtrim( $base, '/' ) ) ) {
		$path = substr( $path, strlen( rtrim( $base, '/' ) ) );
		$path = '' !== $path ? $path : '/';
	}
	return array( $path, spokares_hard_sort_query( $query ) );
}

/**
 * "b=2&a=1" → "a=1&b=2" (the generator sorts the same way).
 *
 * @param string $query Query string.
 */
function spokares_hard_sort_query( string $query ): string {
	if ( '' === $query ) {
		return '';
	}
	$pairs = array_filter( explode( '&', $query ), 'strlen' );
	$pairs = array_map( 'rawurldecode', str_replace( '+', ' ', $pairs ) );
	sort( $pairs, SORT_STRING );
	return implode( '&', $pairs );
}

/**
 * Look a key up in the map, with and without a trailing slash.
 *
 * @param string $path  Path.
 * @param string $query Sorted query ('' for the bare path).
 */
function spokares_hard_redirect_lookup( string $path, string $query ): ?array {
	$map = spokares_hard_redirect_map();
	$alt = '/' !== $path ? ( str_ends_with( $path, '/' ) ? rtrim( $path, '/' ) : $path . '/' ) : $path;
	foreach ( array( $path, $alt ) as $p ) {
		$key = '' === $query ? $p : $p . '?' . $query;
		if ( isset( $map[ $key ] ) && is_array( $map[ $key ] ) ) {
			return $map[ $key ];
		}
	}
	return null;
}

/**
 * Match before WordPress parses the request: the path with its sorted query,
 * then (for ordinary queries) the bare path. Joomla spam queries and
 * /index.php/… paths that aren't in the map are gone (410).
 *
 * @param bool $do Whether WordPress should parse the request.
 */
function spokares_hard_redirects( $do ) {
	if ( is_admin() || wp_doing_ajax() || ( defined( 'REST_REQUEST' ) && REST_REQUEST ) ) {
		return $do;
	}
	[ $path, $query ] = spokares_hard_request_key();
	if ( str_starts_with( $path, '/wp-json' ) || str_starts_with( $path, '/wp-admin' ) || str_starts_with( $path, '/wp-login' ) ) {
		return $do;
	}
	$hit = '' !== $query ? spokares_hard_redirect_lookup( $path, $query ) : null;
	if ( ! $hit && str_contains( $query, 'option=com_' ) ) {
		$GLOBALS['spokares_hard_status'] = 410;
		return $do;
	}
	// WordPress's own index.php?… requests (rest_route, p, preview) are left alone.
	if ( ! $hit && ( '' === $query || '/index.php' !== $path ) ) {
		$hit = spokares_hard_redirect_lookup( $path, '' );
	}
	if ( $hit ) {
		$status = (int) ( $hit[0] ?? 0 );
		$target = (string) ( $hit[1] ?? '' );
		if ( 301 === $status && str_starts_with( $target, '/' ) ) {
			wp_safe_redirect( home_url( $target ), 301, 'spokares' );
			exit;
		}
		if ( 410 === $status ) {
			$GLOBALS['spokares_hard_status'] = 410;
		}
		return $do;
	}
	if ( str_starts_with( $path, '/index.php/' ) ) {
		$GLOBALS['spokares_hard_status'] = 410;
	} elseif ( str_starts_with( $path, '/wp-content/' ) || str_starts_with( $path, '/wp-includes/' ) ) {
		$GLOBALS['spokares_hard_status'] = 404;
	}
	return $do;
}
add_filter( 'do_parse_request', 'spokares_hard_redirects', 0 );

/**
 * Send the 410 (or the plain 404) through the theme's 404 template.
 */
function spokares_hard_gone(): void {
	$status = (int) ( $GLOBALS['spokares_hard_status'] ?? 0 );
	if ( ! $status ) {
		return;
	}
	global $wp_query;
	$wp_query->set_404();
	status_header( $status );
	nocache_headers();
}
add_action( 'template_redirect', 'spokares_hard_gone', 0 );

// Never guess a page for an unknown URL, and never "correct" a gone one.
add_filter( 'do_redirect_guess_404_permalink', '__return_false' );
add_filter(
	'redirect_canonical',
	static function ( $redirect ) {
		return ! empty( $GLOBALS['spokares_hard_status'] ) ? false : $redirect;
	}
);
